/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT
cntry,
COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY cntry
ORDER BY total_customers DESC;
-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;
-- Find total products by category
SELECT category,
COUNT(product_id) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT category,
ROUND(AVG(cost),0) as average_costs
FROM gold.dim_products
GROUP BY category
ORDER BY average_costs DESC;

-- What is the total revenue generated for each category?
SELECT p.category,
SUM(s.sales_amount) as total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue generated by each customer
SELECT c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) as total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
c.cntry as country,
sum(quantity) as sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.cntry
ORDER BY sold_items DESC;